chg in WF (2)

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -35,10 +35,20 @@ jobs:
           node-version: '20'
 
       - name: Install dependencies
-        run: npm ci
+        run: |
+          cd app
+          npm ci   # npm install
+
+      - name: Check package-lock.json
+        run: |
+          ls
+          cd app
+          cat package-lock.json || echo "package-lock.json not found"
 
       - name: Run migrations
-        run: npm run migrate
+        run: |
+          cd app
+          npm run migrate
         env:
           DATABASE_HOST: localhost
           DATABASE_NAME: postgres
@@ -46,7 +56,9 @@ jobs:
           DATABASE_PASSWORD: password
 
       - name: Run tests
-        run: make test
+        run: |
+          cd app
+          make test
         env:
           DATABASE_HOST: localhost
           DATABASE_NAME: postgres
@@ -69,6 +81,7 @@ jobs:
       - name: Build and push Docker image
         uses: docker/build-push-action@v4
         with:
-          context: .
+          #context: .
+          context: ./app  # Указываем путь к директории с проектом
           push: true
           tags: mishaikon/devops-for-programmers-project-74:latest
